package dev.jkcarino.adobo.patches.ninegag.ad

internal const val AD_HOSTS = """
    mxpl.9gag.com
    prod.cm.publishers.advertising.a2z.com
    prod.tahoe-analytics.publishers.advertising.a2z.com
    cdn-f.adsmoloco.com
    amazon-adsystem.com
    app-measurement.com
    admob-gmats.uc.r.appspot.com
    pbs-onboarding-eu.ay.delivery
    pbs-onboarding-us.ay.delivery
    chartboost.com
    protected-by.clarium.io
    cdn.confiant-integrations.net
    firebase-settings.crashlytics.com
    doubleclick.net
    fyber.com
    mediation.goog
    google-analytics.com
    fundingchoicesmessages.google.com
    mobileads.google.com
    www.googleadservices.com
    googlesyndication.com
    googletagservices.com
    inmobi.com
    supply.inmobicdn.net
    cdn2.inner-active.mobi
    sdk-events.inner-active.mobi
    wv.inner-active.mobi
    liveramp.com
    api.mixpanel.com
    sdkapi.dsp-api.moloco.com
    sdkopmetrics-us.dsp-api.moloco.com
    pubnative.net
    api.rlcdn.com
    smaato.com
    smaato.net
    spadsync.com
    telemetry.tk0x1.com
    uidapi.com
    fh.under9.co
    customendcard.verve.com
    feedback.verve.com
    sdkc.vervegroupinc.net
    vrvm.com
    tags-prod.vrvm.com
    vungle.com
"""
